### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by SeptemberMaples** [liepinteam/copy-dir#4]
No compatible version found: copy-dir@0.0.7

error Windows_NT 6.1.7601
error argv "C:\Program Files\nodejs\node.exe" "C:\Users\yangyong\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "copy-dir"
error node v4.4.7
 error npm  v3.10.5
 error No compatible version found: copy-dir@0.0.7
 error Valid install targets:
 error 0.3.0, 0.2.0, 0.1.0, 0.0.8

**Comment by pillys** [comment]
You can use the latest version: `npm install copy-dir@0.3.0`
Have a try?
